### ISSUE TITLE
Udemy "The Complete Elixir and Phoenix Bootcamp"

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-elixir#56]
In order to learn Elixir and Phoenix I'm using the udemy course ["The Complete Elixir and Phoenix Bootcamp"](https://www.udemy.com/the-complete-elixir-and-phoenix-bootcamp-and-tutorial/learn/v4/overview), and at the moment I'm really enjoying it! It is also reduced to £15 at the moment if dwyl wanted a copy of the course to use. 

I found the description and examples of pattern matching especially helpful as this was something I was struggling with understanding through the [Elixir School book](https://elixirschool.com/en/).

I'm only on the third section right now, but I hope to finish the course this week, at which point, assuming I still like it, I'd like to make a PR to add it as a link in the "Further Resources" section.

**Comment by gabrielperales** [comment]
Thank you for sharing!! @ZooeyMiller

**Comment by YvesMuyaBenda** [comment]
@ZooeyMiller Yeah, the Elixir School book would be quite difficult to learn from. The original reason I I thought it useful in the first place was that it at least had a good organisation so that one would know which are the concepts that one needs to learn, and where do they all fit in, and some idea of sequencing, as in, "oh, yes, perhaps I might need to learn what pattern matching is, what protocols are, etc, etc". I view it almost a cross between a dictionary and an encyclopedia.

**Comment by ZooeyMiller** [comment]
I've finished the purely Elixir section, and am now onto the Phoenix section. I really found this beneficial, I already had played with Elixir a little bit, but I like this video series because I find Stephen Grider to be very good at explaining things, and it's a `pay-for-the-course-and-keep-it` model rather than a subscription based model like the [codeschool elixir video course](https://www.codeschool.com/courses/mixing-it-up-with-elixir). (though I've just seen that the codeschool tutorials are free this weekend! :heart_eyes: )

I know @finnhodgkin has finished the whole udemy tutorial, what did you think?

**Comment by finnhodgkin** [comment]
The Udemy series is really great up to the point it cuts out with a 'this series will be updated in the future' note. It's a shame because the part I was most looking forward to—Phoenix sockets—is right where it finishes... Pretty frustrating.

Before that point it's a really great intro to templating with Phoenix, and Elixir in general. But yeah, it'd be good to include a warning before recommending the series.

Has anyone started the codeschool course?

**Comment by ZooeyMiller** [comment]
Having now finished up with the course I definitely think that it's a valuable addition to this repo, but I think just the Elixir bit (section 1 to 6) as the Phoenix tutorial is in Phoenix 1.2, and cuts out before teaching WebSockets, so will make a PR to this repo with a link the the tutorial with this information.

**Comment by iteles** [comment]
I'm in two minds about this one. Whilst I'm always excited to share valuable content, I'm very conflicted about encouraging people to spend money on Udemy because of this https://medium.com/@robconery/how-udemy-is-profiting-from-piracy-5638b929ffca

People will find Udemy anyway, my conflict is more about actively promoting them 😕

**Comment by ZooeyMiller** [comment]
Oh wow, I hadn't seen about that :confused:
It's a shame as I'm not sure if there's a proper bought course (since codeschool is subscription based). Maybe we need to look into making our own!

**Comment by iteles** [comment]
@zooeymiller YES. And I'm not even joking. 
Have a chat with @cleop and @markwilliamfirth - the first step is a video for this readme!

**Comment by ZooeyMiller** [comment]
Awesome! I'd love to do some video tutorial stuff.

**Comment by ZooeyMiller** [comment]
Closing this issue due to the discussion RE udemy's business practices.

**Comment by iteles** [comment]
I AM SO EXCITED
